[settings]
quiet = true
task_output = "interleave"
experimental = true
aqua.registries = ["https://github.com/KnickKnackLabs/bats-core"]

[plugins]
shiv = "https://github.com/KnickKnackLabs/vfox-shiv"

[tools]
"aqua:KnickKnackLabs/bats-core" = "1.14.0-kkl.3"
"aqua:shenwei356/rush" = "0.9.0"
usage = "3.0.0"
gum = "0.17.0"
jq = "1.8.1"
yq = "4.50.1"
coreutils = "0.7.0"
"github:ip7z/7zip" = "26.00"
uv = "0.10.0"
"shiv:codebase" = "0.4"
"shiv:readme" = "0.3"

[_.codebase]
name = "winnie"
lint = ["@all"]
