#!/usr/bin/env bash
# Generate grub.cfg from distro manifests.
# Usage: source this file, then call grub_generate <mount_point>
# Writes to <mount_point>/boot/grub/grub.cfg

grub_generate() {
  local mount_point="$1"
  local grub_dir="$mount_point/boot/grub"
  mkdir -p "$grub_dir"

  cat > "$grub_dir/grub.cfg" << 'GRUBHEAD'
# Auto-generated by winnie disk:add — do not edit manually
set timeout=10
set default=0

insmod all_video
GRUBHEAD

  for manifest in "$mount_point"/distros/*/manifest.json; do
    [[ -f "$manifest" ]] || continue
    local dir slug title kernel initrd params extract_mode install_img
    dir=$(dirname "$manifest")
    slug=$(basename "$dir")

    title=$(jq -r '.title' "$manifest")
    extract_mode=$(jq -r '.extract_mode // "flat"' "$manifest")
    if [[ "$extract_mode" == "tree" ]]; then
      kernel=$(jq -r '.kernel_path' "$manifest")
      initrd=$(jq -r '.initrd_path' "$manifest")
    else
      kernel=$(basename "$(jq -r '.kernel_path' "$manifest")")
      initrd=$(basename "$(jq -r '.initrd_path' "$manifest")")
    fi
    params=$(jq -r '.boot_params' "$manifest")

    # Strip iso-specific params that don't apply to extracted boot
    params=$(echo "$params" | sed 's|findiso=[^ ]*||g; s|iso-scan/filename=[^ ]*||g' | sed 's/  */ /g; s/^ //; s/ $//')

    # Strip splash params — Plymouth can't render its progress bar in QEMU
    # (needs DRM/KMS driver in initramfs, which stock live ISOs don't include
    # for virtual GPUs). Show text boot progress instead.
    # shellcheck disable=SC2016  # intentional: strip the literal GRUB variable name
    params=$(echo "$params" | sed 's|quiet||g; s|splash||g; s|\$extra_kernel_parameters||g' | sed 's/  */ /g; s/^ //; s/ $//')
    params="$params plymouth.enable=0"

    # Ensure boot-media pointers target the extracted location on the winnie drive.
    local squashfs
    squashfs=$(jq -r '.squashfs_path // empty' "$manifest")
    install_img=$(jq -r '.install_img_path // empty' "$manifest")
    if [[ -n "$install_img" ]]; then
      if echo "$params" | grep -q 'inst.stage2='; then
        # shellcheck disable=SC2001  # sed keeps the Anaconda boot-parameter rewrite readable
        params=$(echo "$params" | sed "s|inst.stage2=[^ ]*|inst.stage2=hd:LABEL=WINNIE:/distros/$slug|g")
      else
        params="$params inst.stage2=hd:LABEL=WINNIE:/distros/$slug"
      fi
      if [[ -f "$dir/repodata/repomd.xml" ]] && ! echo "$params" | grep -q 'inst.repo='; then
        params="$params inst.repo=hd:LABEL=WINNIE:/distros/$slug"
      fi
    elif [[ -n "$squashfs" ]]; then
      if echo "$params" | grep -Eq '(^| )rd\.live\.image($| )|root=live:'; then
        if echo "$params" | grep -q 'root=live:'; then
          # shellcheck disable=SC2001  # sed keeps the boot-parameter rewrite readable
          params=$(echo "$params" | sed 's|root=live:[^ ]*|root=live:LABEL=WINNIE|g')
        else
          params="$params root=live:LABEL=WINNIE"
        fi

        if echo "$params" | grep -q 'rd.live.dir='; then
          # shellcheck disable=SC2001  # sed keeps the boot-parameter rewrite readable
          params=$(echo "$params" | sed "s|rd.live.dir=[^ ]*|rd.live.dir=/distros/$slug|g")
        else
          params="$params rd.live.dir=/distros/$slug"
        fi
      elif echo "$params" | grep -q 'live-media-path='; then
        # shellcheck disable=SC2001  # sed keeps the boot-parameter rewrite readable
        params=$(echo "$params" | sed "s|live-media-path=[^ ]*|live-media-path=/distros/$slug|g")
      else
        params="$params live-media-path=/distros/$slug"
      fi
    fi

    {
      echo ""
      echo "menuentry \"$title ($slug)\" {"
      echo "    search --no-floppy --label WINNIE --set=root"
      params=$(echo "$params" | sed 's/  */ /g; s/^ //; s/ $//')
      echo "    linux /distros/$slug/$kernel $params"
      if [[ -n "$initrd" ]]; then
        echo "    initrd /distros/$slug/$initrd"
      fi
      echo "}"
    } >> "$grub_dir/grub.cfg"
  done

  # Utility entries — always present, even on an empty drive
  cat >> "$grub_dir/grub.cfg" << 'GRUBTAIL'

menuentry "Reboot" {
    reboot
}

menuentry "Shutdown" {
    halt
}

menuentry "GRUB Command Line" {
    commandline
}
GRUBTAIL
}
