#!/usr/bin/env bash
# Generate grub.cfg from distro manifests.
# Usage: source this file, then call grub_generate <mount_point>
# Writes to <mount_point>/boot/grub/grub.cfg

grub_generate() {
  local mount_point="$1"
  local grub_dir="$mount_point/boot/grub"
  mkdir -p "$grub_dir"

  cat > "$grub_dir/grub.cfg" << 'GRUBHEAD'
# Auto-generated by winnie disk:add — do not edit manually
set timeout=10
set default=0

insmod all_video
GRUBHEAD

  for manifest in "$mount_point"/distros/*/manifest.json; do
    [[ -f "$manifest" ]] || continue
    local dir slug title kernel initrd params
    dir=$(dirname "$manifest")
    slug=$(basename "$dir")

    title=$(jq -r '.title' "$manifest")
    kernel=$(basename "$(jq -r '.kernel_path' "$manifest")")
    initrd=$(basename "$(jq -r '.initrd_path' "$manifest")")
    params=$(jq -r '.boot_params' "$manifest")

    # Strip iso-specific params that don't apply to extracted boot
    params=$(echo "$params" | sed 's|findiso=[^ ]*||g; s|iso-scan/filename=[^ ]*||g' | sed 's/  */ /g; s/^ //; s/ $//')

    # Rewrite live-media-path to point at extracted location on the winnie drive
    params=$(echo "$params" | sed "s|live-media-path=[^ ]*|live-media-path=/distros/$slug|g")

    {
      echo ""
      echo "menuentry \"$title ($slug)\" {"
      echo "    search --no-floppy --label WINNIE --set=root"
      echo "    linux /distros/$slug/$kernel $params"
      if [[ -n "$initrd" ]]; then
        echo "    initrd /distros/$slug/$initrd"
      fi
      echo "}"
    } >> "$grub_dir/grub.cfg"
  done

  # Utility entries — always present, even on an empty drive
  cat >> "$grub_dir/grub.cfg" << 'GRUBTAIL'

menuentry "Reboot" {
    reboot
}

menuentry "Shutdown" {
    halt
}

menuentry "GRUB Command Line" {
    commandline
}
GRUBTAIL
}
